[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["Robin Beer <r.beer@outlook.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
fastapi = "uvicorn app.main:app --reload"

[dependencies]
fastui = "0.3.0.*"
python = "3.12.0.*"
fastapi = "0.105.0.*"
pydantic = "2.5.2.*"
uvicorn = "0.24.0.post1.*"
sqlmodel = "0.0.14.*"
httpx = "0.25.2.*"
requests = "2.31.0.*"
